import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import yo from "../../public/images/yo.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <p>Este es el index</p>
        <p>
          Ir a hola <Link href="/hola">aquí</Link>
        </p>

        <Image src={yo} height={144} width={144} placeholder="blur" />
      </main>
    </div>
  );
}
